Inverse joint 1 and 5, and tweak arm velocity params
clubcapra/ovis pull request #36
Opened 2023-02-24 15:28 UTC by GLDuval

These tweaks make the arm much smoother when using the UI after these changes https://github.com/clubcapra/capra_web_ui/pull/162. Also the joints 1 and 5 were inverted to improve usability.

2023-02-24 15:29 UTC, saxtot approved these changes
Simple enough!

2023-02-24 17:20 UTC, Leo-Dan requested changes
Seems good to me. I would like to add another velocity constant for the axis 4-5-6 of the robot. They could move a lot faster than the others (1-2-3) because of their reduced inertia. 
It would make inspection tasks easier IMO ;).

2023-02-27 18:24 UTC, GLDuval commented
> Seems good to me. I would like to add another velocity constant for the axis 4-5-6 of the robot. They could move a lot faster than the others (1-2-3) because of their reduced inertia. It would make inspection tasks easier IMO ;).

Good suggestion, I'll try to sit down Wednesday and fine tune it!

2023-03-02 19:38 UTC, Leo-Dan approved these changes

2023-03-02 19:38 UTC, merged